twitter:
  my_screen_name:
    june29
  consumer_key:
    xxxxx
  consumer_secret:
    xxxxx
  access_key:
    xxxxx
  access_secret:
    xxxxx
matchers:
  keywords:
    - 大和田
    - じゅーん
    - 準二級
    - ガローア
    - ゴールデンボンバー
  regexp:
    (?<!とて)もじゃ
notifiers:
  boxcar:
    email:
      xxxxx
    provider_key:
      xxxxx
    provider_secret:
      xxxxx
  imkayac:
    username:
      june29
  pushover:
    user_token:
      xxxxx
    app_token:
      xxxxx
    sound:
      magic
    priority:
      1
    device:
      Nexus4
linker:
  http
